FROM elestio/etherpad:latest
LABEL MAINTAINER="OSU Open Source Lab <dockerhub@osuosl.org>"
RUN pnpm run install-plugins ep_adminpads2 ep_chatdate ep_desktop_notifications \
    ep_hide_referrer ep_small_list ep_comments_page ep_author_hover ep_webrtc
