#!/bin/bash

set -e

echo $DOBC_PASSWORD | passwd dobc --stdin

# ensure variables passed to docker container are also exposed to ssh sessions
env | grep _ >> /etc/environment

if [ -z "$@" ] ; then
  ssh-keygen -A
  exec /usr/sbin/sshd -D
else
  "$@"
fi
