name: UBI Image Builder

on:
  workflow_dispatch: 
  push: 
    paths:
      - 'ubi-ppc64le/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'ubi-ppc64le'

jobs:
    build-ubi-builder-img:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and export Docker image
              uses: docker/build-push-action@v5

            - name: Log in to the Container Registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build & Push Image
              uses: docker/build-push-action@v6
              with:
                push: true
                context: "{{defaultContext}}:ubi-ppc64le"
                platforms: linux/ppc64le
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}