---
name: ubi-ppc64le

on:
  push:
    branches:
      - master
    paths: ubi-ppc64le/*
  pull_request:
    paths: ubi-ppc64le/*
  schedule:
    - cron: '15 20 * * 2'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ubi-ppc64le

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: ubi-ppc64le
          tags: osuosl/ubi-ppc64le:test
          platforms: linux/ppc64le
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Log in to the Container Registry
        if: contains(fromJSON('["push", "schedule"]'), github.event_name)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        if: contains(fromJSON('["push", "schedule"]'), github.event_name)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=schedule,${{ github.ref_name }}
      - name: Build and push Docker image
        if: contains(fromJSON('["push", "schedule"]'), github.event_name)
        uses: docker/build-push-action@v5
        with:
          context: ubi-ppc64le
          push: true
          tags: ghcr.io/osuosl/ubi-ppc64le:latest
          platforms: linux/ppc64le
          labels: ${{ steps.meta.outputs.labels }}
